Fix bashism/non-POSIX usage of $UID.

diff --git a/sbin/grml-network b/sbin/grml-network
--- a/sbin/grml-network
+++ b/sbin/grml-network
@@ -9,9 +9,8 @@
 PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin"
 export PATH
 
-if [ $UID != 0 ] ; then
-   echo Error: become root before starting $0 >& 2
-   exit 100
+if [ $(id -ru) -ne 0 ] ; then
+  echo 1>&2 "Error: please run this script with uid 0 (root)." ; exit 1
 fi
 
 # XDIALOG_HIGH_DIALOG_COMPAT=1
diff --git a/sbin/grml-pptp-inode b/sbin/grml-pptp-inode
--- a/sbin/grml-pptp-inode
+++ b/sbin/grml-pptp-inode
@@ -14,9 +14,8 @@
 
 export LANG=C
 
-if [ $UID != 0 ] ; then
-   echo Error: become root before starting $0 >& 2
-   exit 100
+if [ $(id -ru) -ne 0 ] ; then
+  echo 1>&2 "Error: please run this script with uid 0 (root)." ; exit 1
 fi
 
 if [ -z "$FORCE_OLD" ] ; then
@@ -46,7 +45,7 @@ EOF
 echo "${VPNUSERNAME} XDSL ${VPNPASSWORD} *" >> /etc/ppp/pap-secrets
 chmod 0600 /etc/ppp/pap-secrets
 
-echo -e "#!/bin/sh\nLANG=C\nVPNSERVER=\"${VPNSERVER}\"\n" > /etc/init.d/pptp
+printf "#!/bin/sh\nLANG=C\nVPNSERVER=\"${VPNSERVER}\"\n" > /etc/init.d/pptp
 
 cat >> /etc/init.d/pptp << "EOF"
 
diff --git a/sbin/grml-vnet b/sbin/grml-vnet
--- a/sbin/grml-vnet
+++ b/sbin/grml-vnet
@@ -16,6 +16,9 @@ OPT_GROUP_=''
 OPT_BRIDGE_=''
 OPT_AUTO_='false'
 
+if [ $(id -ru) -ne 0 ] ; then
+  echo 1>&2 "Error: please run this script with uid 0 (root)." ; exit 1
+fi
 
 function printUsage()
 {
diff --git a/sbin/modemlink b/sbin/modemlink
--- a/sbin/modemlink
+++ b/sbin/modemlink
@@ -12,9 +12,8 @@ export PATH
 # XDIALOG_HIGH_DIALOG_COMPAT=1
 # export XDIALOG_HIGH_DIALOG_COMPAT
 
-if [ $UID != 0 ] ; then
-   echo Error: become root before starting $0 >& 2
-   exit 100
+if [ "$(id -u 2>/dev/null)" != 0 ] ; then
+  echo 1>&2 "Error: please run this script with uid 0 (root)." ; exit 1
 fi
 
 TMP=$(mktemp)
